 const blogContent=[
     {Title: "Rise Against", 
     Info:"Rise Against is an American punk rock band from Chicago, formed in 1999. The group's current line-up comprises vocalist/rhythm guitarist Tim McIlrath, lead guitarist Zach Blair, bassist Joe Principe and drummer Brandon Barnes. Rooted in hardcore punk and melodic hardcore, Rise Against's music emphasizes melody, catchy hooks, an aggressive sound and playstyle, and rapid tempos. Lyrically, the band is known for their outspoken social commentary, covering a wide range of topics such as political injustice, animal rights, humanitarianism, and environmentalism.The band spent its first four years signed to the independent record label Fat Wreck Chords, on which they released two studio albums, The Unraveling (2001) and Revolutions per Minute (2003). Both the albums were met with underground success, and in 2003 the band signed with the major label Dreamworks, which was absorbed by Geffen. Rise Against's major label debut Siren Song of the Counter Culture (2004) brought the band mainstream success, largely in part to the popularity of the singles Give It All and Swing Life Away. The band's next album, The Sufferer & the Witness (2006), peaked at number ten on the Billboard 200 in the United States, and was Rise Against's first album to chart in countries outside of North America. With the release of Appeal to Reason (2008), Rise Against's music shifted toward a more accessible and radio-friendly sound, with greater emphasis on production value. The album's third single, Savior, broke the record for the most consecutive weeks spent on both the Hot Rock Songs and Alternative Songs charts. Rise Against's popularity grew with the release of Endgame (2011), which peaked at number two on the Billboard 200, and charted highly worldwide. The band's 7th and 8th albums, The Black Market (2014) and Wolves (2017) continued the trend of commercial success, and both peaked with the top ten on the Billboard 200."},
     {Title: "Anti-Flag",
      Info:"Anti-Flag is an American punk rock band from Pittsburgh, Pennsylvania, United States. The band is well known for its left-wing political activism. The lineup includes singer/guitarist Justin Sane and drummer Pat Thetic, who founded the band together; later members are guitarist Chris Head, and singer/bassist Chris Barker (#2) who replaced Jamie Cock Towns, who had replaced original bassist Andy Flag in 1997 following his departure one year prior. Anti-Flag is known also for their advocacy of progressive political action groups such as Greenpeace and Amnesty International, and the Occupy movement."},
     {Title:"Ramones",
      Info:"The Ramones were an American punk rock band that formed in the New York City neighborhood of Forest Hills, Queens, in 1974. They are often cited as the first true punk rock group. Despite achieving only limited commercial success initially, the band was highly influential in the United States, Argentina, Brazil and most of South America, as well as Europe, including the United Kingdom, the Netherlands, Germany, Sweden and Belgium. All of the band members adopted pseudonyms ending with the surname Ramone, although none of them were biologically related; they were inspired by Paul McCartney of the Beatles, who would check into hotels as Paul Ramon. The Ramones performed 2,263 concerts, touring virtually nonstop for 22 years. In 1996, after a tour with the Lollapalooza music festival, they played a farewell concert in Los Angeles and disbanded. By 2014, all four of the band's original members had died – lead singer Joey Ramone (1951–2001), bassist Dee Dee Ramone (1951–2002), guitarist Johnny Ramone (1948–2004) and drummer Tommy Ramone (1949–2014).The remaining surviving members of the Ramones—bassist C. J. Ramone (who replaced Dee Dee in 1989 and stayed with the band until its dissolution) and drummers Marky Ramone, Richie Ramone and Elvis Ramone—are still musically active."},
     {Title: "Streetlight Manifesto",
      Info:"Streetlight Manifesto is an American ska punk band from New Brunswick, New Jersey, United States, formed in 2002. They released their first album, Everything Goes Numb, which was distributed by Victory Records, on August 26, 2003. The band headlined and sold out their first concert at Rutgers University in New Brunswick, New Jersey on December 9, 2003. Several of Streetlight Manifesto's members were well known in the New Jersey third wave ska community for their roles in past ska punk bands from that area, primarily Kalnoky's Catch 22 and fellow New Jersey band One Cool Guy."},
     {Title: "Reel Big Fish",
      Info:"Reel Big Fish is an American ska punk band from Orange County, California. The band gained mainstream recognition in the mid-to-late 1990s, during the third wave of ska with the release of the gold certified album Turn the Radio Off. Soon after, the band lost mainstream recognition but gained an underground cult following. As of 2006, the band was no longer signed to a major record label and has since been independent. After numerous line-up changes, frontman Aaron Barrett is the last remaining founding member still performing in the band."},
     {Title:"A Day to Remember",
      Info:"A Day to Remember (often abbreviated ADTR, and previously known as End of an Era) is an American rock band from Ocala, Florida, founded in 2003 by guitarist Tom Denney and drummer Bobby Scruggs. They are known for their amalgamation of metalcore and pop punk. The band currently consists of vocalist Jeremy McKinnon, rhythm guitarist Neil Westfall, percussionist/drummer Alex Shelnutt and lead guitarist Kevin Skaff. Signing with Indianola Records for their first album, And Their Name Was Treason (2005), Scruggs was replaced by Shelnutt in 2006. Later that year the band recorded For Those Who Have Heart (2007) for Victory Records. They embarked on several tours of the UK and U.S. and played at several festivals before recording and releasing Homesick (2009). While promoting Homesick on tour, Denney was replaced by Skaff. Soon after releasing their next album, What Separates Me from You (2010), the band went on a worldwide tour to promote it. Since 2011, the band has been involved in a lawsuit with Victory Records over their recording contract. In October 2013 the band was given the right to self-release new albums until a final verdict is reached. They released their fifth album, Common Courtesy, that month. In 2016, the band released their sixth album, Bad Vibrations. They released their seventh album You're Welcome on March 5, 2021, which marked their first release under Fueled by Ramen."},
     {Title:"Sum 41",
      Info: "Sum 41 is a Canadian rock band from Ajax, Ontario. Originally called Kaspir, the band was formed in 1996 and currently consists of Deryck Whibley (lead vocals, guitars, keyboards), Dave Baksh (lead guitar, backing vocals), Jason Cone McCaslin (bass, backing vocals), Tom Thacker (guitars, keyboards, backing vocals), and Frank Zummo (drums, occasional backing vocals). In 1999, Sum 41 signed an international record deal with Island Records and released its first EP, Half Hour of Power, in 2000. The band released its debut album, All Killer No Filler, in 2001. The album achieved mainstream success with its first single, Fat Lip, which reached number one on the Billboard Modern Rock Tracks chart and remains the band's most successful single to date. The album's next singles In Too Deep and Motivation also achieved commercial success. All Killer No Filler was certified platinum in both the United States and the United Kingdom and triple platinum in Canada.[1] In 2002, the band released Does This Look Infected?, which was also a commercial and critical success. The singles The Hell Song and Still Waiting both charted highly on the modern rock charts. The band released its next album, Chuck, in 2004, led by singles We're All to Blame and Pieces. The album proved successful, peaking at number 10 on the Billboard 200. In 2007, the band released Underclass Hero, which was met with a mixed reception, but gained some commercial success, becoming the band's highest charting album to date. It was also the band's last album on Aquarius Records. The band released the album Screaming Bloody Murder, on Island Records in 2011 to a generally positive reception, though it fell short of its predecessors' commercial success. The band's sixth studio album, 13 Voices was released in 2016. IMPALA awarded the album with a double gold award for 150,000 sold copies across Europe.[2][3] The band's seventh studio album Order in Decline was released on July 19, 2019."},
     {Title:"Rancid",
      Info:"Rancid is an American punk rock band formed in Berkeley, California in 1991. Founded by former members of the band Operation Ivy, Rancid is often credited as being among the wave of bands that revived mainstream interest in punk rock in the United States during the mid-1990s. Over their 30-year career, Rancid retained much of its original fan-base, most of which was connected to its underground musical roots. Rancid has had two lineup changes since its inception, with Tim Armstrong and Matt Freeman being continuous members. Their current lineup consists of Armstrong on guitar and vocals, Freeman on bass and vocals, Lars Frederiksen on guitar and vocals, and Branden Steineckert on drums. The band was formed by Armstrong, Freeman, and former drummer Brett Reed, who left the band in 2006 and was replaced by Steineckert. This lineup recorded their first album, with Frederiksen joining the band on their subsequent tour."}
 ]

 export default blogContent